### ISSUE TITLE
Rejecting & accepting websockets

### ISSUE THREAD

**Issue by TheChifer** [fdimuccio/play2-sockjs#20]
I would like to reject & accept websockets based on the session status, something like what play2 websockets supports

public LegacyWebSocket<String> socket() {
    if (session().get("user") != null) {
        return WebSocket.withActor(MyWebSocketActor::props);
    } else {
        return WebSocket.reject(forbidden());
    }
}

What is the api support for this?

**Comment by fdimuccio** [comment]
You can do it in the same way:

```scala
import play.sockjs.SockJS;
import play.sockjs.SockJSRouter;
import play.mvc.*;

public class Reject extends SockJSRouter {

    @Override
    public SockJS sockjs() {
        if (session().get("user") != null) {
            return SockJS.withActor(MyWebSocketActor::props);
        } else {
            return SockJS.reject(forbidden());
        }

    }
}
```

Note that you need to use at least 0.5.1-SNAPSHOT because I fixed a bug that caused the http context to not be available when creating the SockJS java handler.
