### ISSUE TITLE
Play 2.7 released

### ISSUE THREAD

**Issue by Flo354** [fdimuccio/play2-sockjs#27]
Hi there :)

Play 2.7 is now stable (version 2.7.0). Will you update the module?

Thanks,

**Comment by Flo354** [comment]
In mode "quick & dirty", I made two modifications to make it work again temporary:

=> In JavaRouter.scala
`protected def materializer: Materializer = play.api.Play.unsafeApplication.materializer`

=> In CookieFunctions
`return new Http.Cookie("JSESSIONID", value, null, "/", null, false, false, Http.Cookie.SameSite.STRICT);`

I don't think it's the good way, since Play team recommends using dependency injection since `play.allowGlobalApplication` is now "false" by default.

**Comment by mellster2012** [comment]
For play scala the above fix for CookieFunctions seems sufficient to make sockjs work with play 2.7.0

**Comment by mellster2012** [comment]
https://github.com/fdimuccio/play2-sockjs/pull/28

Refactored for DI.

**Comment by fdimuccio** [comment]
I merged the PR and released 0.7.0. 

Thank you for your effort.
