### ISSUE TITLE
Play 2.8.0 support

### ISSUE THREAD

**Issue by Flo354** [fdimuccio/play2-sockjs#32]
Hi there,

Play 2.8.0 is not released. Could you make it compatible?

Thanks,

**Comment by fdimuccio** [comment]
Hi,

I just published the artifacts for 2.8.0. The version is 0.8.0, please give some time to the artifact to be replicated on maven central.

**Comment by Flo354** [comment]
Thanks @fdimuccio for still maintaining the library!
